# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 17:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180503_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='intitiative3Body',
            new_name='intitiativesBody',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative1Body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative1Link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative1Title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative2Body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative2Link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative2Title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative3Link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intitiative3Title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='regionalBody',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondaryBody',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
