# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180507_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='updatesMore',
            field=models.CharField(default='See all updates', max_length=100),
        ),
    ]
