# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_resourcepage_embedsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='embedIntro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='embedSRC',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='embedTitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
